### ISSUE TITLE
RADS - ACS/PUMS income distribution not working

### ISSUE THREAD

**Issue by aschachter** [PHSKC-APDE/rads#102]
I tried using 'income6' as the "what" to generate an income distribution for King County using ACS PUMS data, and received the following error message:

> results <- rads::calc(copy(person.design), 
+                       what = 'income6', 
+                       chi_geo_kc==1,
+                       time_var = "year.int", 
+                       metrics = c("numerator", "denominator", "mean"))
Error in svyby(as.formula(paste0("~`__dv__`")), bys, svy, svyciprop, na.rm = T) : 
  could not find function "svyby"

It looks like installing the "survey" package solves the issue. RADS should check to ensure the package is installed.

Full reproducible code: 

rm(list=ls()) # clear memory
library(data.table)
library(srvyr)
library(rads)

## get pums data ----
load("//Phshare01/epe_share/WORK/surveys/ACS/PUMS data & code all years/2014_2018_5_year/prepped_R_files/2014_2018_5_year_data.RData")

# need to create an integer 'year' for RADS ----
person.wa[year == "2014-2018", year.int := 1L]

# Survey set the WA data ----
person.design <-     # person level survey setting for 5-year data
  srvyr::as_survey_rep(
    person.wa ,
    weights = pwgtp ,
    combined.weights = TRUE ,
    repweights = grep('pwgtp[0-9]+', names(person.wa), value  = T) ,
    scale = 4 / 80 ,
    rscales = rep( 1 , 80 ) ,
    mse = TRUE ,
    type = "JK1"
  )

# use rads to get estimated % of population by income
results <- bind_rows(results, rads::calc(copy(person.design), 
                      what = 'income6', 
                      chi_geo_kc==1,
                      time_var = "year.int", 
                      metrics = c("numerator", "denominator", "mean")))

**Comment by dcolombara** [comment]
Could not replicate the error. Ran the code below and it worked perfectly fine without adding `survey` or `srvyr` packages.

rm(list=ls()) # clear memory
library(data.table)
library(rads)

load("//Phshare01/epe_share/WORK/surveys/ACS/PUMS data & code all years/2014_2018_5_year/prepped_R_files/2014_2018_5_year_data.RData")

person.wa[year == "2014-2018", year.int := 1L]


person.design <- # person level survey setting for 5-year data
  srvyr::as_survey_rep(
    person.wa ,
    weights = pwgtp ,
    combined.weights = TRUE ,
    repweights = grep('pwgtp[0-9]+', names(person.wa), value = T) ,
    scale = 4 / 80 ,
    rscales = rep( 1 , 80 ) ,
    mse = TRUE ,
    type = "JK1"
  )

results <- rads::calc(person.design,
                               what = 'income6',
                               chi_geo_kc==1,
                               time_var = "year.int",
                               metrics = c("numerator", "denominator", "mean"))
