### ISSUE TITLE
numerator returns whacky large number when using ndistrinct metric

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/rads#103]
**Describe the bug**
When counting the number of distinct values of a column using rads::calc(), a ridiculously large numerator is returned

**To Reproduce**
test_birth <- rads::get_data_birth(cols = c("birth_cert_encrypt", "date_of_birth_year", "date_of_birth_month", "source_of_payment"))
rads::calc(test_birth, what = "birth_cert_encrypt", time_var = "date_of_birth_year", metrics = c("ndistinct")) - BROKEN
rads::calc(test_birth, what = "date_of_birth_month", time_var = "date_of_birth_year", metrics = c("ndistinct")) - WORKS
rads::calc(test_birth, what = "sex", time_var = "date_of_birth_year", metrics = c("ndistinct")) - WORKS

**Expected behavior**
The numerator doesn't really have any meaning if only ndistinct is called. I would expect it to match the ndistinct column or be null. But even if it is the number of values with that level, it clearly goes wrong in some cases.

**Comment by dcolombara** [comment]
rads::calc(test_birth, what = "birth_cert_encrypt", time_var = "date_of_birth_year", metrics = c("ndistinct", "numerator"))
rads::calc(test_birth, what = "birth_cert_encrypt", metrics = c("numerator"))[]
rads::calc(test_birth, what = "date_of_birth_month", time_var = "date_of_birth_year", metrics = c("ndistinct", "numerator"))

**Comment by dcolombara** [comment]
Will be fixed in next iteration of data.table, when we address https://github.com/PHSKC-APDE/rads/issues/119
