### ISSUE TITLE
Allow read_data to run if columns are missing

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/rads#112]
Currently read_data_hys (and possibly other data sources) will fail if a column specified does not exist:
hys <- get_data_hys(year = c(2008:2018), cols = c("year", "hopescale", "l02", "l03", "l04", "l05", "l06", "kingco"), kingco = T)
Error: Can't subset columns that don't exist.
x Columns l02, l03, l04, l05, l06, etc. don't exist.

This is because the subsetting happens here after the data are read in: https://github.com/PHSKC-APDE/rads/blob/master/R/get_data.R#L89

It might be better to do a check of the names of the variables present in the data and match against the desired list. Anything that is not present could be excluded from the subset command but a warning given to the user.

**Comment by dcolombara** [comment]
FIXED for get_data_birth. STill needs to be fixed for get_data_hys
