### ISSUE TITLE
Subset error with calc function

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/rads#114]
Running the calc function with a by variable is producing an error that didn't used to be there:
_Error in dumb_convert(get(byc[x]), by_class[[x]]) : 
  length(target) == 1 is not TRUE_

Running rlang::last_error() and rlang::last_trace() give a bit more info:
_Can't subset elements that don't exist.
 Location 1 doesn't exist.
 There are only 0 elements._

It looks the each year of analysis is run (2008 to 2018) even though HYS is only available for even-numbered years. The error seems to occur when there is an attempt to subset the results to years where data are present.

**To Reproduce**  
    ```
    library(rads)
    
    what.prop.vars <- c("hopescale", "s15", "s16", "l02", "l03", "l04", "l05", "l06")
    
    by.vars <- c("kingco", "a_aian_aic", "a_as_cambodian_aic", "a_as_chinese_aic", "a_as_filipino_aic", 
                 "a_as_indian_aic", "a_as_japanese_aic", "a_as_korean_aic", "a_as_other_aic", 
                 "a_as_vietnamese_aic", "a_asian_aic", "a_black_aic", "a_grade", "a_his_aic", 
                 "a_nhpi_aic", "a_oth_aic", "a_race8", "a_sex", "a_sexorien3", "a_wht_aic", "kc4reg")

    hys <- get_data_hys(year = c(2008:2018), cols = c("year", what.prop.vars, by.vars), kingco = T)

    hys <- hys %>%
      mutate(hopescale = case_when(hopescale %in% c(1:3) ~ 0L, hopescale == 4 ~ 1L)) %>%
      mutate_at(vars(s15, s16), list(~ case_when(. %in% c(1, 2) ~ 0L, . %in% c(3, 4) ~ 1L)))

    temp.results <- calc(hys,
                     what = "s15",
                     by = "kingco",
                     metrics = c("mean", "rse"),
                     win = 2,
                     time_var = "year",
                     proportion = TRUE)

```

**Expected behavior**
Analyses performed for each year and then restricted to years for which we have data.

**Comment by dcaseykc** [comment]
Will be fixed by #151 and 1.0.0 I think
