### ISSUE TITLE
Standardize how race/ethnicity gets returned/reported

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#120]

**Comment by dcolombara** [comment]
What are the standards?

In the [Tableau style guide](https://kc1.sharepoint.com/:w:/r/sites/APDETableauresources/_layouts/15/Doc.aspx?sourcedoc=%7B359811A5-92B0-4B13-B6DC-DD71CDBBA11B%7D&file=Tableau%20Style%20Guide%20v1.0.4.docx&action=default&mobileredirect=true&cid=c219bed9-ac3a-4e78-b521-beff9ee81938) the best that I found is on page 9:

- Asian
- AIAN
- Black
- Hispanic
- NHPI
- Multiple race
- White
- Other race

In the [APDE Analysis guide](https://kc1.sharepoint.com/:w:/r/teams/PHc/datareq/_layouts/15/WopiFrame.aspx?sourcedoc=%7b03674a42-971d-442b-a332-2bbd7b355e2c%7d&action=edit&cid=f0f5570e-2893-4fbe-83a9-f0fc24ccb49e) (page 12) there is the following list: OMB97

- Asian, 
- American Indian/Alaska Native,  
- Black, 
- Hispanic, 
- Native Hawaiian/Pacific Islander, 
- Multiple Race, 
- White) 

Or, should we go with the legit/exact names in [OMB 97](https://orwh.od.nih.gov/toolkit/other-relevant-federal-policies/OMB-standards)?

Which set do you want returned? I'm inclined to return the short ones and post a file to GitHub [reference-data](https://github.com/PHSKC-APDE/reference-data) with cross-walk of short to long race/eth names. 

Thoughts?

**Comment by dcaseykc** [comment]
I'm inclined to use the short names and have people merge on the bigger/longer names if they want.
