### ISSUE TITLE
Add toggle for other counties to get_population

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#136]
Suggestion from Amy on 8/3/2021

**Comment by dcolombara** [comment]
@jwhitehurst-KC  ... is this possible? Do we receive population data for all WA counties and only load that for KC and adjoining?

**Comment by jwhitehurst-KC** [comment]
We get info for all WA counties but only load king, snohomish, and pierce. This was just how it was always done. If there are others we need we probably need a larger conversation as county data is the largest dataset.

**Comment by dcolombara** [comment]
Sounds good. I will put it on my list to discuss with Amy next time we have a 1:1. If she wants to pursue this, we can have a larger conversation.

**Comment by dcolombara** [comment]
dropped for now because want to focus on KC unless there is a contract.
