### ISSUE TITLE
rate not returned from calc function

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#138]
Calc.data.frame does not return values for rate

`
library(data.table)
library(rads)

blah <- data.table(a = 1:200, b = c("A", "B"), ttt = sample(1:3, 200, T))

rads::calc(blah, 'a', metrics = rads::metrics(),
           per = 1, win = 2, time_var = 'ttt',
           proportion = F, fancy_time = T, by = "b",
           ci = .95)[]
`

**Comment by dcaseykc** [comment]
I'm going to start including it with the dtsurvey stuff. That sound ok?

**Comment by dcolombara** [comment]
Yes, that makes sense.

**Comment by dcaseykc** [comment]
Addressed by #143 I think

**Comment by dcaseykc** [comment]
This should be done once 1.0.0 is released
