### ISSUE TITLE
add rads.data to dependancy

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#144]
Thoughts @dcolombara

**Comment by dcaseykc** [comment]
Or to be more useful. Is this something we need to do? Or should it be suggested people install the thing?

**Comment by dcolombara** [comment]
Yes, I think we should. But, only after we decide that rads.data is definitely going to exist. Once we finalize that decision and set it as a dependency, I can update some of the code that currently refers to GitHub reference-data.
