### ISSUE TITLE
Get rid of joinpoint 

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#163]
Can we do this?

**Comment by dcaseykc** [comment]
@dcolombara

**Comment by dcolombara** [comment]
Did I create that function? It doesn't seem like it's the way I would code? 

Regardless, I think it's good to take out the dplyr dependency, especially if it is the only one in RADS. When I have time (someday I hope!) maybe I can revise it to use data.table and then add it back in.
