### ISSUE TITLE
remove dplyr dependency

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#176]
Split this off of Issue #163 because they are two separate things

**Comment by dcolombara** [comment]
I deleted joinpoint, so now dplyr is only used in some misc code that you wrote. I am guessing it is all okay to delete, but I want to check with you first. 

The relevant code is all in the following three directories

1) https://github.com/PHSKC-APDE/rads/tree/master/snippets ... old and not structured as useful functions
2) https://github.com/PHSKC-APDE/rads/tree/master/doc  ... the hys files 
3) https://github.com/PHSKC-APDE/rads/tree/master/explorations ... `compare_tbl_svy_tbl_dt.R`, `hys.Rmd`, `hys_scratch.R`

If / when you give the okay, I'll make this code disappear.

**Comment by dcaseykc** [comment]
I think you can get rid of that. Thanks!
