### ISSUE TITLE
How to read things from sharepoint

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#182]

**Comment by dcolombara** [comment]
KCIT Incident | Ticket 501952 on **1/31/20222**
> Danny would like to access Sharpoint data with this R plugin from Microsoft: https://github.com/Azure/Microsoft365R
> 
> When attempting to log in he receives the attached error.
> 
> AzureR/Microsoft365R needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

My follow-up on **2/2/2022**
> This is relatively pressing because it informs whether we will move any datafiles to SharePoint. If KCIT could allow permission for the following app registration, I think it would work: https://github.com/Azure/Microsoft365R/blob/master/inst/app_registration.md

**Comment by dcolombara** [comment]
This has been addressed. For example, see https://github.com/PHSKC-APDE/rads.data/blob/main/data-raw/misc_chi_byvars.R where we pull data from Joie's reference sheet in SharePoint. 

Generally, it's a terrible idea to store data on SharePoint, but we have the ability when it is necessary.
