### ISSUE TITLE
Export summary data, specifying file types, options, and location

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#195]
Export summary data (tables, graphs, etc.), specifying file types (.csv, .xlsx, pdf, .png, .tif, etc.), options (e.g., dimensions and dpi for images), and location

**Comment by dcaseykc** [comment]
Do we really need to abstract this? Whats wrong with write.csv?

**Comment by dcolombara** [comment]
I agree. I was just transferring items from our to do spreadsheet, I'm not sure that all of these make sense. 

If there is ever a shiny type front end, then maybe this would be useful. However, `write.csv` or `fwrite` is fine for most purposes and `openxlsx::write.xlsx()` is easy to implement. 

If / when we build something for mapping our data (which is a distinct issue) this may have more relevance.

**Comment by dcolombara** [comment]
Currently irrelevant so closing without further work / exploration.
