### ISSUE TITLE
life expectancy

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#197]
Initial exploration in [danny's repo](https://github.com/PHSKC-APDE/pers_dvc/blob/main/R/life_expectancy_exploration.R)

**Comment by dcaseykc** [comment]
This is more of ETL, right?

**Comment by dcolombara** [comment]
life_table() function pushed to dev on 3/8/2022. Will need wrapper to grab and collapse/prep deaths and population for the function.

**Comment by dcolombara** [comment]
finished as part of death_functions update (rads version 1.1.3).
