### ISSUE TITLE
implement list_dataset_columns

### ISSUE THREAD

**Issue by rwbuie** [PHSKC-APDE/rads#214]
currently list_dataset_columns is not operational. Create preliminary version that returns variable names from selected database. Replace query for database names in get_data with this function. 

Next iteration, create detection or config file input functionality for identifying and reporting types of variables (analytics output vs individual case level).

**Comment by dcolombara** [comment]
fixed with commit aeb3164f03a7144f06dbc70301d9b90fe5da28d3
