### ISSUE TITLE
Clearer errors when dealing with empty DTs

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/rads#217]
If I add a silly where statement that leads to the data table having 0 rows I get a fairly uninterpretable error. Could you please add a check for a zero-row DT when applying the where filter and return a message that lets users know?

Reproducible example:
```
library(odbc)
library(rads)
library(tidyverse)
library(srvyr)

db_apde <- DBI::dbConnect(odbc::odbc(),
                          driver = "ODBC Driver 17 for SQL Server",
                          server = "KCITSQLPRPDBM50",
                          database = "PH_APDEStore",
                          Encrypt = "yes",
                          TrustServerCertificate = "yes",
                          Authentication = "ActiveDirectoryIntegrated")

bskhs <- dbGetQuery(db_apde, "SELECT * FROM final.bskhs_2017_2021")

### set up data survey
bskhs_svy <- bskhs %>%
  mutate(c_id = ifelse(is.na(c_id), -1, c_id),
         w_rwt_scaled = ifelse(is.na(w_rwt_scaled), 0, w_rwt_scaled)) %>%
  as_survey_design(ids = c_id, strata = w_region, weights = w_rwt_scaled, nest = T)

bskhs_svy_rads <- dtsurvey::as.dtsurvey(bskhs_svy)
```

WORKS:
```
calc(ph.data = bskhs_svy_rads, what = "c_internet",
     where = (year %in% c("2021")),
     metrics = c("mean", "rse"),
     by = c("c_langhome"), proportion = T,
     fancy_time = T)
```

GENERATES ERROR:
```
calc(ph.data = bskhs_svy_rads, what = "c_internet",
     where = (year %in% c("2021") & c_langhome == "22"),
     metrics = c("mean", "rse"),
     by = c("c_langhome"), proportion = T,
     fancy_time = T)
```

_Error in data.table:::`[.data.table`(x = res, j = `:=`(c("mean", "mean_se",  : 
Supplied 4 columns to be assigned an empty list (which may be an empty data.table or data.frame since they are lists too). To delete multiple columns use NULL instead. To add multiple empty list columns, use list(list())._

Also, if there is a zero-row DT resulting from the where statement, calc does not like time windows:
```
calc(ph.data = bskhs_svy_rads, what = "c_internet",
     where = (year %in% c("2021") & c_langhome == "22"),
     metrics = c("mean", "rse"),
     by = c("c_langhome"), proportion = T,
     win = 1, time_var = "year", 
     fancy_time = F)
```

_Error in lapply(wins, function(w) { : object 'wins' not found_

**Comment by dcaseykc** [comment]
@alastairmatheson and @dcolombara : Should things error out, or return a mostly nonsensical/NULL data.table? For example, I have some code that'll have that first block that generates an error return:

```
structure(list(c_langhome = integer(0), variable = character(0), 
    level = logical(0), mean = numeric(0), mean_se = numeric(0), 
    mean_lower = numeric(0), mean_upper = numeric(0), rse = numeric(0)), row.names = integer(0), class = c("data.table", 
"data.frame"), .internal.selfref = <pointer: 0x0000024ca55c1ef0>)
```

**Comment by dcaseykc** [comment]
I'm now inclined to error if where reduces things to 0 row objects but allow the inner layer to just get away with a warning.

**Comment by dcaseykc** [comment]
Some tentative changes in #218. Check out tests/testthat/test_calc.dtsurvey.R for more info. Short version is, what I've implemented now will return NAs/NaNs/character(0) etc. The alternative is change line 45ish in calc.dtsurvey (which reads `if(nrow(ph.data) == 0) warning('No valid rows to compute on given `where` conditions')`) to be an error via `stop`. I'll leave it to the crew what the answer should be

**Comment by alastairmatheson** [comment]
My inclination is to return the empty DT and issue a warning. My preference for that over a stop error is that if you are feeding calc a bunch of what variables and only some error out based on the where statement, you wouldn't want the whole thing to stop.

**Comment by dcaseykc** [comment]
@alastairmatheson: At present, the returned object isn't exactly empty (which would be nrow =0). Instead its nrow of 1 with some NAs and what not. Would you prefer it return something of nrow 0?

**Comment by dcolombara** [comment]
I agree with Alastair. I think I'd prefer a null / empty table and a warning so that loop isn't broken. I'm fine with a true empty table (zero rows), as long as it is structured correctly for easy rbinds with other actual calc results.

**Comment by alastairmatheson** [comment]
I think rows with 0s/NAs etc. is better than a truly null table so it's still visible, along with the warning.

**Comment by rwbuie** [comment]
Just thinking through what would be needed for a run_chi or other looping function, I would prefer a DF or DT with 0 rows but the correct headers. This also let's rbind work without throwing errors or junk data.

**Comment by dcolombara** [comment]
I agree with Ron. However, I can also see the value of of table with NA values. I know I sometimes ignore warnings, but it's hard to ignore a row of NAs. @dcaseykc  ... maybe you should flip a coin?

**Comment by dcaseykc** [comment]
Updated #218 to reduce the amount of warning messages and also return a 0 row data.table with all the correct columns when a particular combination is 0 row as well.

**Comment by alastairmatheson** [comment]
One more request for the warning: could you output the where/win statements that lead to the zero rows? I'm realizing that if I am running a bunch of variables through in a loop, I can't tell which combos led to the zero rows.

**Comment by dcaseykc** [comment]
@alastairmatheson : Can you see if the latest commit does what you want? Otherwise, I'd consider trying to capture the warnings from your calc command and then scan through them after the fact.

**Comment by alastairmatheson** [comment]
That should do the trick as long as you're not using a kludgy eval(pasrse(..)) setup in the where statement
