### ISSUE TITLE
add std.error function

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#229]
R doesn't have a built in function for the standard error of the mean. This seems to be a commonly calculated number in epi so let's add it to RADS. 

Check out ... 
https://github.com/plotrix/plotrix/blob/master/R/std.error.R

**Comment by dcaseykc** [comment]
isn't it just `sqrt(sd(x))`? Where `x` is a vector of numbers.

**Comment by dcolombara** [comment]
almost. it is `sd/sqrt(x)` where x is the length of vector you mentioned. 
it's slightly annoying to calc when there are missing values in a data.table and I'm trying to calc the standard error by groups (because lengths of each group need to account for the fact that I'm using na.rm = T to calc the sd. 

There is zero urgency and I'll code it when I work on rads again unless you're opposed to including it.

**Comment by dcolombara** [comment]
done! Commit 420dfdb0dc317ff4685a6a48dfb14ea83a62c2ff
