### ISSUE TITLE
Add IQR as a metric for calc?

### ISSUE THREAD

**Issue by dcolombara** [PHSKC-APDE/rads#230]
Could we / should we add the interquartile range as a metric / output for the calc function?

Discuss when we have time and are working on rads again.

**Comment by dcaseykc** [comment]
but whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by dcolombara** [comment]
We don't have to. It came up in a recent project where I helped other APDE staff with their analysis. I just skipped using rads and calculated mean/median/iqr using data.table, but it might be nice for others. No strong feelings on this one way or the other.

**Comment by dcolombara** [comment]
Let's drop this for now unless there is a definite ask. We have enough to do!
