### ISSUE TITLE
improve error message in life_table() when fed duplicate observations

### ISSUE THREAD

**Issue by rwbuie** [PHSKC-APDE/rads#307]
life_table() receives a DT with ages, number of deaths, fractional weight, population, and any other independent variables desired by the user. Each combination of ages and other variables must be unique (e.g., there cannot be 2 rows with "male" ages "0-1".) If non unique rows are received, life_table() throws an error from being unable to recognize the age ranges, rather than recognizing the redundant rows. This error is:

"Error in life_table(ph.data = DT) : 
  The final age in 'myages' (i.e., ages) must be in the form #+, e.g., '85+' or '90+'"

A quality check should probably be executed at the start of the function that confirms that the provided table has no repitions of age+[dependent variables] combinations, and a user friendly error message provided if this condition is not met.

A more accurate, (but verbose) error would read something like:

“non unique rows detect in the provided data. This may be due to errors in preparing your data. Each row should be a unique combination of ‘myages’, and your chosen independent variables. E.g. if preparing a life_table subsetting on gender, you should not have 2 rows with gender as ‘male’ and age as ‘0-1’”

**Comment by dcolombara** [comment]
Must have been fixed at some point. I just ran an example or a life table grouped_by gender (following the example in the wiki). I repeated the row for Males 85+ and in a separate trial repleated the row for Males 0-1. In both cases I received the following error:
``` 
> dt9.lifetable <- life_table(ph.data = dt9, group_by = 'gender')

Error in life_table(ph.data = dt9x, group_by = "gender") : 
👿 The values in 'myages' (i.e., ages) must be unique for each combination of the values in the `group_by` variables
