### ISSUE TITLE
Results in vignette include both males and females but sample code selects for female population estimates

### ISSUE THREAD

**Issue by MTa2018APDE** [PHSKC-APDE/rads#310]
Hello Daniel and Danny.

This is not critical or urgent.  I noticed that the example in the get-population vignette for "King County regions stratified by year -- Female Hispanic and Asian-NH residents aged 16-25 only -- not rounded" includes both males and females in the displayed results but the code is selecting for female population estimates.  When I run the code in my version of RStudio the result only had the value of “female” in the gender column. 

For reference, I've summarized screenshots in the following Word document.

[RADS_getpop_vignette_issue.docx](https://github.com/PHSKC-APDE/rads/files/12384166/RADS_getpop_vignette_issue.docx)

Thank you for your time in  fixing with the next update and for your efforts in maintaining this community resource for APDE.

With appreciation,
Myduc

**Comment by dcolombara** [comment]
fixed on 9/19/2023.
