### ISSUE TITLE
Add ethnicity to the group_by options

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#333]

**Comment by csjohns** [comment]
DCHS would like to be able to include ethnicity (hispanic/not hispanic) as an option to group by, so as to be able to have both race and ethnicity as different data dimensions.  Adding comment for the record I know Daniel gets it :)

**Comment by dcolombara** [comment]
Fixed #333 with commit fdea4e213fc4520e395577cc891ff7a934323246
