### ISSUE TITLE
Instructions - additional details/adjustments

### ISSUE THREAD

**Issue by mckenziem** [PHSKC-APDE/rads#66]
1.) The instructions should mention that "PHSKC-APDE/apdeRecodes” and "PHSKC-APDE/rads" have to be downloaded every time Rstudio is restarted.

2.) In the instructions, the first example using the get_data_birth function says, “Let’s try the function to see how it works by loading the year and King County columns for WA State in 2018”. This confused me because I thought the chi_geo_kc column was King County data only. However, it appears from the birth recodes csv that this column may be of all WA counties; the old_var says “mother_residence_county_wa_code”. 

Perhaps the example needs to say, “Let’s try the function to see how it works by loading the year and county columns for WA State in 2018”?
I was confused at first because I wasn’t understanding why setting Kingco=F vs Kingco=T was pulling different number of observations if chi_geo_kc was supposed to be King County only.

Dimensions:
When Kingco=F the dimensions are 87249 & 2
When Kingco=T the dimensions are 24337 & 2

3.) For the calc function, the instructions say the argument “by” should be a character vector to compute the “what” by. In the example below, the “calc single years” example uses chi_year year which is an integer in class. When I used the argument win=1. I received the same output. Perhaps, the example should be adjusted or the instructions next to the by statement should be adjusted.

4.) For "Custom sub-populations", I think additional explanations regarding the ability to add custom calculations and specifications beyond in the underlying coded arguments is possible. I didn't know additional arguments could be created when using a pre-made function. Specifically thinking about the "calc Medicaid births, first time moms, under 23, by HRA and by race" example.

**Comment by dcolombara** [comment]
These comments do not represent items to be corrected, but rather misunderstandings. There is nothing to be done.
