### ISSUE TITLE
Outputs - double check that the outputs in the instructions are the same as in Rstudio

### ISSUE THREAD

**Issue by mckenziem** [PHSKC-APDE/rads#67]
I know there were some additional updates to the underlying births data table. Some of the output may have adjusted. Specifically check “calc 5 year rate per 100,000”.

Beyond that, I would make sure that the exact output in Rstudio should be placed in the instructions (e.g., show both levels in the instructions like it is shown in Rstudio).

**Comment by dcolombara** [comment]
The user must have had an old vignette. Since the vignette should be produced each time the package is updated, they should not get out of sync.
