### ISSUE TITLE
Recode in instructions - code may need to be adjusted

### ISSUE THREAD

**Issue by mckenziem** [PHSKC-APDE/rads#68]
In the example regarding “Intersection of Low Birth Weight & Prematurity in KC (last 5 years combined)”, the creation and recode for preterm_lbw did not work.

I think it didn't work because "preterm" and "bw_low" class are factors and the code referenced their underlying values. When I adjusted the code to preterm == “Yes” & bw_low == “Yes”, it worked. 

So instead of " birth[, preterm_lbw := 0][preterm == 1 & bw_low == 1, preterm_lbw := 1]" the code in the instructions should be adjusted to "birth[, preterm_lbw := 0][preterm == “Yes” & bw_low == “Yes”, preterm_lbw := 1]"

**Comment by dcolombara** [comment]
Unsure why this didn't work for Maya. Just tested the relevant code in the vignette and it works perfectly.
