### ISSUE TITLE
Try to capture combinations in 'what' and 'by' that will generate errors

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/rads#82]
See comment here: https://github.com/PHSKC-APDE/rads/issues/81#issuecomment-591626262

**Comment by dcaseykc** [comment]
I'm not sure really what this issue is referring to anymore. I'm going to close it and hope that it magically fixes itself in RADS 1.0.0 (to be released). @dcolombara or @alastairmatheson : Feel free to post a reprex/additional explanation if your memory is better.
