### ISSUE TITLE
ndistinct when what is a factor

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#94]
When `what` is a factor or character variable, what should ndistinct be: 1 or 2 or # of categories?

See/run the second test in https://github.com/PHSKC-APDE/rads/blob/dcc_dev/tests/testthat/test_calc_consistency.R for an example.

**Comment by dcolombara** [comment]
As commented in #118, using ndistinct for the number of levels of the factor sounds reasonable (although not necessary).
